
#ifndef ARRS_CONSTANTS_H
#define ARRS_CONSTANTS_H

#define MAX_TICKET_COUNT 100
#define DEFAULT_RIDE_TIME 5
#define DEFAULT_RIDE_COUNT 5
#define REPOSITORY_INITIAL_CAPACITY 10
#endif //ARRS_CONSTANTS_H
